/**
 * Creates a GitHub Pull Request via the REST API.
 */
export async function createPR({ owner, repo, githubToken, prompt, defaultBranch = 'main' }) {
  const title = `AI: ${prompt.slice(0, 72)}`
  const body = [
    '## Changes Generated by Plasma AI',
    '',
    `**Prompt:** ${prompt}`,
    '',
    '---',
    '_This pull request was automatically created by [Plasma AI](https://github.com)._',
  ].join('\n')

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `token ${githubToken}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title,
      head: 'xibecode-ai-change',
      base: defaultBranch,
      body,
    }),
  })

  const data = await response.json()

  if (!response.ok) {
    throw new Error(data.message || `GitHub PR creation failed (${response.status})`)
  }

  return {
    url: data.html_url,
    number: data.number,
    title: data.title,
  }
}
